### ISSUE TITLE
[Feature] Better Discord/GitHub release notes parity

### ISSUE THREAD

**Issue by IvanMazzoli** [rommapp/romm#1173]
**Is your feature request related to a problem? Please describe.**
I'm on both the Discord and here on GitHub and I'm being notified on both when a new release is available. But I noted that the one on GitHub is far more "technical" and it's missing some info that the Discord displays, for example you can check the release notes for 3.5.1 here and on the Discord to see the differences (eg. the Unraid install instructions update, no mentions about it here).
It should also be noted that not everyone has a Discord account, or they don't want to join a channel (are they called that?) just to have a more detailed changelog.

**Describe the solution you'd like**
I think a mix of the Discord release notes format and the one here on GH could be better for everyone that don't have or don't want to use Discord. A good example of a template you could adopt it's from the Immich project: https://github.com/immich-app/immich/releases/tag/v1.113.0

**Describe alternatives you've considered**
Joining the Discord channel. Although it seems like a waste to use it just to see in detail what's new, since I don't use it to ask for support there - which in my opinion should only be requested here on GitHub so that others with similar problems can easily find the solution and not endlessy scroll a chat, but this that's another matter.

**Additional context**
You can easily see what's better to read between the two release notes. SPOILER: the one behind the Discord join wall.

![discord](https://github.com/user-attachments/assets/5b69008b-e3e7-4604-a008-cba0c599e541)
![github](https://github.com/user-attachments/assets/80b795b8-fa55-4451-8e95-32acc4b1bd62)

**Comment by gantoine** [comment]
Yeah I think this is a reasonable ask, we'll start using a better format for github releases in 3.6.0.

> which in my opinion should only be requested here on GitHub so that others with similar problems can easily find the solution and not endlessy scroll a chat

The issue with that is 90%+ of the support requests that come in are related to setting up romm, or some specific issue with a user's config/mount binds, which isn't applicable to most people. Our github issues would be flooded with the same requests all the time, which is harder to manage.

If an actual bug/issue comes in we ask them to post it here so that others can see it, and we can backlog it (see the 99% Decompression issue with EmulatorJS). Our internal roadmap for bug fixes is based on github issues, so bug reports need to exist here so we can work on them.

**Comment by IvanMazzoli** [comment]
Thanks for clarifying my thoughts on the issues.
I completely agree with you, if most of the questions are asking for help on Romm setup there is no problem having a separate chat on Discord where you can share your knowledge.
On the contrary, as I rightly see has been done, issues such as login problems should be shared here on GitHub.

That said, thank you so much for considering my suggestion about release notes!
