### ISSUE TITLE
[Bug] Renaming games that contains accents breaks urls, and thus breaks download and play for that game.

### ISSUE THREAD

**Issue by outerwinnie** [rommapp/romm#1212]
**RomM version**
3.5.1

**Describe the bug**
When using the renaming option in RomM, if the game has an accent the filename is going to have it too and that breaks urls. (and thus download and play options for that game)

**To Reproduce**

1. Pick any Pokémon game for example
2. Use the renaming function of RomM with the rom
3. Try to download it, or play it

**Expected behavior**
RomM shouldn't add accents to filenames.

**Comment by adamantike** [comment]
I don't think the expected behavior here is to not add accents to the files. Ideally, any character supported by the filesystem should not be removed from filenames, to not enforce the user to a reduced charset.

Instead, this sounds more like failing to correctly quote some of the URLs, to escape any special characters.

**Comment by adamantike** [comment]
A fix for this has been merged, and will be available in the next release!
