### ISSUE TITLE
[Feature] Default to using platform specific album art

### ISSUE THREAD

**Issue by Aasikki** [rommapp/romm#1317]
Would be nice if the default art used were the platform specific ones that include the systems name-banner.
EDIT: Also would be really nice if platform accurate aspect ratios were supported, as in support the more square art that ps1 cases have. Why? Idk it would just give that nice and fuzzy feeling in my heart lol, would feel just a bit more like browsing though a physical collection.

**Describe alternatives you've considered**
Manually swapping art for every single game.

**Additional context**
Not sure if any of the api's used for downloading album art would support this,

**Comment by zurdi15** [comment]
Having different aspect ratio per platform was impemented in #1324 and will be available in the next release 3.7.0. However, selecting a "kind" of default cover like the original box art will be difficult to implement since the scan process uses the IGDB covers as default. You will need to manually select the proper cover from the SteamgridDB

**Comment by Aasikki** [comment]
> Having different aspect ratio per platform was impemented in #1324 and will be available in the next release 3.7.0. However, selecting a "kind" of default cover like the original box art will be difficult to implement since the scan process uses the IGDB covers as default. You will need to manually select the proper cover from the SteamgridDB

That's awesome! I understand automating it would be challenging, but being able to do it manually is already really nice.
