### ISSUE TITLE
[Bug] Cant run docker as user

### ISSUE THREAD

**Issue by Gibbz** [rommapp/romm#1327]
**RomM version**
Latest docker

**Describe the bug**
In the docker file i want to be able to run as a standard user, not requiring root. So I add to the docker-compose.yml user: 1000:1000
However the docker fails to load the config file and doesnt load.

**To Reproduce**
Add user: 1000:1000 to the docker-compose

**Expected behavior**
Should be able to work in non-root environment

**Comment by mikhailv** [comment]
For me it works well, I used `3.6.0-rc.1` and now updated to latest `3.6.0`, works as a charm. What error do you have exactly?

**Comment by Gibbz** [comment]
okay. It works now that the docker data has been initialized. It does not work on the first load.... Should I close this bug in this case?

**Comment by mikhailv** [comment]
Oh, if your container has any volume mounts that does not exist on host, such directories will be created using root user (docker daemon), so later the process in the container will not be able to write anything to such directory because it is running with `1000:1000` in your case. So before starting such container you need to be sure that mount directories exist on host with correct owner.

Not a bug I think.
