### ISSUE TITLE
[Feature] Firmware section

### ISSUE THREAD

**Issue by calebsmithdev** [rommapp/romm#230]
**Describe the solution you'd like**
It would be nice to have a section that is specifically for listing files like firmware or keys. Maybe like an "Extra" for a system or something? Example - the Switch has keys and firmware for each version. It would be nice to be able to navigate to a folder with those so I could download them directly to my Steam Deck.

**Additional context**
I don't think this needs to be anything consistent, maybe just an `extras` folder in the same directory as the `roms` folder and read the files as is.

**Comment by XargonWan** [comment]
For example I got a bios folder that is being scanned only because it's inside the roms folder.

FYI: we in RetroDECK got a tool for checking the bioses if you need some inspirtation: https://github.com/XargonWan/RetroDECK/blob/f6d596152e99bfa87c15103607bec965d3eba74d/tools/configurator.sh#L640

**Comment by zurdi15** [comment]
This is already taken into account. EmuDeck folder structure was the base for the design and it has the following folders:
 - ``roms``
 - ``saves``
 - ``bios`` / ``firmware``
 - etc...

So it is just a matter of time to have more sections for this kind of files. In the future the path of each 'section' will be configurable but for the first iteration I will stick with the EmuDeck structure, having the ``bios/firmware`` folder outside of ``roms`` folder

**Comment by Typhonragewind** [comment]
@XargonWan Any plans on making a Romm integration in RetroDeck (via some sort of API) - so users can just input their Romm settings and access the library in the device where RetroDeck is installed

**Comment by zurdi15** [comment]
Well first of all, sorry for my bad english as it is not my main language:

We talked in the past about [collaborating togheter](https://github.com/zurdi15/romm/issues/30) to make a stronger software ecosystem but I refused because the nature of my personal situation makes me having some periods of hard work and some periods of not having time to put in any kind of personal project, being unable to collaborate or having a compromise with other developers. This was also empowered by the fact that the code base of RomM still needs a lot of work in terms of design and refactor.

However this projects is getting so much bigger than I thought at first, so I have been wondering for several days about having a collaboration with @XargonWan at least in terms of designing the same solutions for the most common problems (savefiles, folder structures, dlc/updates management, etc) and setting some standards in the emulation/games preservation community. He helped me a lot and he already have been analyzing some of the most common problems/features the users are asking for.

I think the wind is changing :)
