### ISSUE TITLE
[Feature] Platform support for Tiger Gizmondo, Tapwave Zodiac

### ISSUE THREAD

**Issue by ameturpoet** [rommapp/romm#762]
**Is your feature request related to a problem? Please describe.**
Not problem related.

**Describe the solution you'd like**
Platform scanner support for the Tiger Gizmondo and Tapwave Zodiac, along with respective platform icons.

**Comment by Casuallynoted** [comment]
I can definitely contribute icons for this, but is it currently not scanning properly when using the IGDB slug names for both those systems? IGDB uses:

zod (for Tapwave Zodiac), and
gizmondo (for the Gizmondo)

**Comment by ameturpoet** [comment]
Oh, is there already support for it? It wasn't on the RomM supported platforms list, so I assumed it wasn't supported as of yet.

**Comment by Casuallynoted** [comment]
> Oh, is there already support for it? It wasn't on the RomM supported platforms list, so I assumed it wasn't supported as of yet.

It should be, I know IGDB has been adding a lot more platforms more recently (such as the Apple Pippin), so anything that IGDB has is currently supported as long as the folder is named according to the slug (internal name) IGDB uses for it :) You can find the full list at IGDB's platforms page, since it's been changing so much lately this should be super helpful:

https://www.igdb.com/platforms

But nonetheless I'll still see if I can get those icons in :P

**Comment by gantoine** [comment]
Thanks for the heads up, the wiki page has been updated 👍🏼
