### ISSUE TITLE
[Feature] detailed installation tutorial

### ISSUE THREAD

**Issue by jecogeo** [rommapp/romm#856]
**Is your feature request related to a problem? Please describe.**
No. Actually, I’m not used to docker. So I feel I’m not savvy enough to get it running. Not sure what to modify on yml files and etc. So a detailed example installation would be good. Something like a tutorial.

**Comment by iroQuai** [comment]
Ive used docker quite some time now and i normally have no problem installing new docker stacks, but this one doesnt seem to work! Keep on getting a restarting problem (although maybe this problem is unrelated to good documentation)

**Comment by gantoine** [comment]
@iroQuai What problem are you seeing exactly? Any way you can dump the logs so we can have a look?

**Comment by iroQuai** [comment]
> @iroQuai What problem are you seeing exactly? Any way you can dump the logs so we can have a look?

I've created a new issue for this, because the problem doesn't seem to be a lack of detailed explanation how docker compose works.

**Comment by iroQuai** [comment]
@jecogeo what part don't you understand? Maybe reading some more about how docker compose works helps. Check out this info for instance: https://docs.linuxserver.io/general/docker-compose/#single-service-usage

**Comment by iroQuai** [comment]
I also stumbled upon this article about the docker basics:

https://nerdyarticles.com/docker-101/

**Comment by EddieDover** [comment]
Honestly, this whole thing seems like a mess if you're on a Windows system.  Docker tries to use WSL if you have it, so the paths needed are either in windows escaped format or nix format based on WSL pathing.  If you're using an external drive and if you're using WSL, then you'll also need to manually set up the mount points for the drives.  

After you get it running, the documentation says we're looking at localhost:8080, but it's running on localhost:80. Also, it looks like editing the ROMM_AUTH username/password doesn't actually do anything, since the only thing that works for me is admin/''.  I'd start to assume it's a caching issue with the compose file, but I had to change the DB_PASSWD and that worked just fine. I even deleted the containers (multiple times) just to make sure.

All in all, the setup documentation makes far too many assumptions about the user base. On top of that, I still can't actually get the app to see the bind points, despite trying every pathing method for the mounts that I can think of in the limited time I'm willing to give this app.

Take this as feedback if you like, but it's definitely not a cry for help. By the time anyone reads this, I've already moved on to something else.

**Comment by gantoine** [comment]
Thanks for the feedback @EddieDover. Truth is self-hosting on windows is a recipe for disaster, so all our instructions assume you're running this on a dedicated linux machine (or unraid/proxmox/casaos/nix). I'm going to respond to some of your points, if only for the next person who sees this thread.

>  If you're using an external drive and if you're using WSL, then you'll also need to manually set up the mount points for the drives.

Mounting external drives at static mount points is the recommended approach in linux. For example, I mount my external drive at `/nas1`, then bind mount the path of my rom library.

> The documentation says we're looking at localhost:8080, but it's running on localhost:80

I'm not sure why you're seeing that, but the webserver runs at `8080`. It's the port we expose in the `Dockerfile`, and the one I use in my `Caddyfile` (reverse proxy).

> Also, it looks like editing the ROMM_AUTH username/password doesn't actually do anything

That's correct, they're only used the first time to generate the admin user. We are planning to move this to an in-product onboarding step on first run, since it doesn't _have_ to be an env variable.

> I still can't actually get the app to see the bind points

Again this is likely a windows/wsl issue, or a permission issue with running on windows. If someone sees this and is planning to run it on windows, i'd _strongly_ recommend running it on a dedicated machine with linux (raspberry pi, nuc, old laptop, potato, etc.)
